### ISSUE TITLE
Jest run tests: Cannot read property 'RNGeocoder' of undefined

### ISSUE THREAD

**Issue by apoorva-techie** [devfd/react-native-geocoder#99]
Hi,

While running npm tests i am getting this error in the application

` ● Test suite failed to run

    TypeError: Cannot read property 'RNGeocoder' of undefined

      at Object.<anonymous> (node_modules/react-native-geocoder/js/geocoder.js:4:41)
      at Object.<anonymous> (node_modules/react-native-geocoder/index.js:1:252)`

Any ideas how to mock this?

**Comment by ezranbayantemur** [comment]
Did you tried `cd ios && pod install`?
